### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by MiaoMiaoYoung** [SunitaG/Multi-modal-medical-image-synthesis#4]
Do you have a paper or BibTeX for your brilliant work？I want to cite your work.

**Comment by SunitaG** [comment]
Right now, there's no paper published. However, I will update the repository if there is one.

**Comment by SunitaG** [comment]
Here's the Bibtex 

@software{sunitag_2020_4250632,
  author    = {SunitaG},
  title        = {SunitaG/Multi-modal-medical-image-synthesis v1.0},
  month    = nov,
  year       = 2020,
  publisher    = {Zenodo},
  version      = {v1.0},
  doi          = {10.5281/zenodo.4250632},
  url          = {https://doi.org/10.5281/zenodo.4250632}
}

**Comment by MiaoMiaoYoung** [comment]
Thanks！
